### ISSUE TITLE
size mismatch

### ISSUE THREAD

**Issue by aaman-ee** [tomfalainen/neural-word-search#1]
Hi, when i run 
python test.py -weights models/dct_washington_fold1_dtp_train_pretrained_seed123_best_val.pt

I get the following error:

`Traceback (most recent call last):
  File "test.py", line 49, in <module>
    model.load_weights(opt.weights)
  File "/home/angelos/PycharmProjects/untitled2/ctrlfnet_model.py", line 165, in load_weights
    self.load_state_dict(torch.load(weight_file))
  File "/home/angelos/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 777, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CtrlFNet:
        size mismatch for box_scoring_branch.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([2]).
        size mismatch for box_scoring_branch.weight: copying a param with shape torch.Size([1, 512]) from checkpoint, the shape in current model is torch.Size([2, 512]).
`

I have the gw_20p_wannot under data/washington and  dct_washington_fold1_dtp_train_pretrained_seed123_best_val.pt under models

Thanks!

**Comment by kapitsa2811** [comment]
+1
